In [291]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [292]:
df = pd.read_csv('México por IQR2.csv')
df =df.drop(labels=["Unnamed: 0"], axis=1)
df

id           source  \
0                    35797      city scrape   
1                    44616  previous scrape   
2                    67703      city scrape   
3                    70644      city scrape   
4                   107078      city scrape   
...                    ...              ...   
26577  1252141718111439700      city scrape   
26578  1252159821531694005      city scrape   
26579  1252185591721328995      city scrape   
26580  1252218347521498445      city scrape   
26581  1252229157495978163      city scrape   

                                                   name  \
0                                           Villa Dante   
1                                          Condesa Haus   
2                     2 bedroom apt. deco bldg, Condesa   
3      Beautiful light Studio Coyoacan- full equipped !   
4                                    NEW  DESIGNER LOFT   
...                                                 ...   
26577    Charming 2-Bedroom Retreat in Lomas de Bezares   
26578                     Suite King | District Polanco   
26579                     Suite King | District Polanco   
26580                    Suite Queen | District Polanco   
26581                  Pretty, well centered, amenities   

                                             description  \
0      Dentro de Villa un estudio de arte con futon, ...   
1      A new concept of hosting in mexico through a b...   
2      Comfortably furnished, sunny, 2 bedroom apt., ...   
3      COYOACAN designer studio quiet & safe! well eq...   
4      Is the best ever place triple L <br />Location...   
...                                                  ...   
26577  Experience Mexico City in this delightful retr...   
26578  This spacious room features a plush king-size ...   
26579  Discover the essence of luxury in our king-siz...   
26580  Welcome to your refuge in the heart of Polanco...   
26581  Known as New Polanco, the Granada colony has p...   

                                   neighborhood_overview    host_id  \
0      Santa Fe Mall, Interloma Park and the Lion Des...     153786   
1                                          Not available     196253   
2                                          Not available     334451   
3      Coyoacan is a beautiful neighborhood famous fo...     212109   
4      Is located in the best area of Mexico City, Po...     540705   
...                                                  ...        ...   
26577  Welcome to Lomas de Bezares, a neighborhood kn...   67472234   
26578                                      Not available  596009321   
26579                                      Not available  596009321   
26580                                      Not available  596009321   
26581                                      Not available    6522855   

        host_name  host_response_time host_is_superhost  \
0            Dici  a few days or more                 f   
1        Fernando      within an hour                 t   
2        Nicholas      within an hour                 t   
3          Trisha  within a few hours                 t   
4          Andrea      within an hour                 t   
...           ...                 ...               ...   
26577     HostPal      within an hour                 t   
26578  Luis Angel      within an hour                 f   
26579  Luis Angel      within an hour                 f   
26580  Luis Angel      within an hour                 f   
26581    Salvador      within an hour                 t   

      neighbourhood_cleansed  ... minimum_nights_avg_ntm  \
0      Cuajimalpa de Morelos  ...                    1.0   
1                 Cuauhtémoc  ...                    1.0   
2                 Cuauhtémoc  ...                    2.0   
3                   Coyoacán  ...                    3.7   
4             Miguel Hidalgo  ...                    1.0   
...                      ...  ...                    ...   
26577         Miguel Hidalgo  ...              

In [293]:
df.columns

Index(['id', 'source', 'name', 'description', 'neighborhood_overview',
       'host_id', 'host_name', 'host_response_time', 'host_is_superhost',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'amenities',
       'has_availability', 'first_review', 'last_review', 'instant_bookable',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'minimum_nights',
       'maximum_nights', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'host_response_rate',
       'host_acceptance_rate', 'price', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'review_scores_rating',
       'review_scores_accu

In [294]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26582 entries, 0 to 26581
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   id                                            26582 non-null  int64  
 1   source                                        26582 non-null  object 
 2   name                                          26582 non-null  object 
 3   description                                   26582 non-null  object 
 4   neighborhood_overview                         26582 non-null  object 
 5   host_id                                       26582 non-null  int64  
 6   host_name                                     26582 non-null  object 
 7   host_response_time                            26582 non-null  object 
 8   host_is_superhost                             26582 non-null  object 
 9   neighbourhood_cleansed                        26582 non-null 

**instant_bookable vs availability_30, host_acceptance_rate, price & beds**

In [295]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep=df[['availability_30','host_acceptance_rate','price','beds']] #De tipo numérico
Var_Dep=df['instant_bookable']

In [296]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [297]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)

In [298]:
#Se escalan todos los datos
escalar = StandardScaler()

In [299]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [300]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [301]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [302]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [303]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[4454  385]
 [2669  467]]


In [304]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision1 = precision_score(y_test, y_pred, average="binary", pos_label="t")
print("Precisión del modelo: ")
print(precision1)

Precisión del modelo: 
0.5481220657276995


In [305]:
from sklearn.metrics import precision_score

precision2 = precision_score(y_test, y_pred, average="binary", pos_label="f")
print("Precisión del modelo: ")
print(precision2)

Precisión del modelo: 
0.6252983293556086


In [306]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud1 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud1)

Exactitud del modelo: 
0.6170532915360502


In [307]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad1 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad1)

Sensibilidad del modelo: 
0.14891581632653061


In [308]:
from sklearn.metrics import recall_score

sensibilidad2 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad2)

Sensibilidad del modelo: 
0.9204381070469105


**source vs availability_30, price, latitude & longitude**

In [309]:
Vars_Indep=df[['availability_30','price','latitude','longitude']] #De tipo numérico
Var_Dep=df['source']

In [310]:
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)


In [311]:
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [312]:
y_pred = algoritmo.predict(X_test)
y_pred
#

array(['city scrape', 'city scrape', 'city scrape', ..., 'city scrape',
       'city scrape', 'city scrape'], dtype=object)

In [313]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[6924  160]
 [ 790  101]]


In [314]:
from sklearn.metrics import precision_score

precision3 = precision_score(y_test, y_pred, average="binary", pos_label="city scrape") 
print("Precisión del modelo: ")
print(precision3)

Precisión del modelo: 
0.8975887995851698


In [315]:
from sklearn.metrics import precision_score

precision4 = precision_score(y_test, y_pred, average="binary", pos_label="previous scrape") 
print("Precisión del modelo: ")
print(precision4)

Precisión del modelo: 
0.38697318007662834


In [316]:
from sklearn.metrics import accuracy_score

exactitud2 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud2)

Exactitud del modelo: 
0.8808777429467085


In [317]:
from sklearn.metrics import recall_score

sensibilidad3 = recall_score(y_test, y_pred, average="binary", pos_label="city scrape")
print("Sensibilidad del modelo: ")
print(sensibilidad3)

Sensibilidad del modelo: 
0.9774138904573687


In [318]:
from sklearn.metrics import recall_score

sensibilidad4 = recall_score(y_test, y_pred, average="binary", pos_label="previous scrape")
print("Sensibilidad del modelo: ")
print(sensibilidad4)

Sensibilidad del modelo: 
0.11335578002244669


**host_is_superhost vs host_response_rate & review_scores_rating**

In [319]:
Vars_Indep=df[['host_response_rate','host_acceptance_rate','review_scores_rating']] #De tipo numérico
Var_Dep=df['host_is_superhost']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [320]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [321]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3921 1004]
 [2468  582]]


In [322]:
from sklearn.metrics import precision_score

precision5 = precision_score(y_test, y_pred, average="binary", pos_label="t") 
print("Precisión del modelo: ")
print(precision5)

Precisión del modelo: 
0.3669609079445145


In [323]:
precision6 = precision_score(y_test, y_pred, average="binary", pos_label="f") 
print("Precisión del modelo: ")
print(precision6)

Precisión del modelo: 
0.6137110658945062


In [324]:
exactitud3 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud3)

Exactitud del modelo: 
0.5646394984326019


In [325]:
sensibilidad5 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad5)

Sensibilidad del modelo: 
0.19081967213114753


In [326]:
sensibilidad6 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad6)

Sensibilidad del modelo: 
0.7961421319796954


**has_availability vs availability_30, price & availability_60**

In [327]:
Vars_Indep=df[['availability_30','price','availability_60']] #De tipo numérico
Var_Dep=df['has_availability']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [328]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [329]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[   0   13]
 [   0 7962]]


In [330]:
precision7 = precision_score(y_test, y_pred, average="binary", pos_label="t") 
print("Precisión del modelo: ")
print(precision7)

Precisión del modelo: 
0.9983699059561129


In [331]:
precision8 = precision_score(y_test, y_pred, average="binary", pos_label="f") 
print("Precisión del modelo: ")
print(precision8)

Precisión del modelo: 
0.0


c:\Users\lalob\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [332]:
exactitud4 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud4)

Exactitud del modelo: 
0.9983699059561129


In [333]:
sensibilidad7 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad7)

Sensibilidad del modelo: 
1.0


In [334]:
sensibilidad8 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad8)

Sensibilidad del modelo: 
0.0


**neighbourhood_cleansed vs latitude & longitude**

In [335]:
unico = np.unique(df["neighbourhood_cleansed"])
unico

array(['Azcapotzalco', 'Benito Juárez', 'Coyoacán',
       'Cuajimalpa de Morelos', 'Cuauhtémoc', 'Gustavo A. Madero',
       'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras',
       'Miguel Hidalgo', 'Milpa Alta', 'Tlalpan', 'Tláhuac',
       'Venustiano Carranza', 'Xochimilco', 'Álvaro Obregón'],
      dtype=object)

In [336]:
barrio_mas_frecuente = df['neighbourhood_cleansed'].value_counts()
barrio_mas_frecuente


neighbourhood_cleansed
Cuauhtémoc                12231
Miguel Hidalgo             4533
Benito Juárez              3152
Coyoacán                   1719
Álvaro Obregón             1075
Tlalpan                     812
Venustiano Carranza         734
Gustavo A. Madero           506
Cuajimalpa de Morelos       442
Iztacalco                   399
Azcapotzalco                349
Iztapalapa                  266
La Magdalena Contreras      143
Xochimilco                  143
Tláhuac                      50
Milpa Alta                   28
Name: count, dtype: int64

In [337]:
df['neighbourhood_cleansed']= df['neighbourhood_cleansed'].replace(['Azcapotzalco', 'Benito Juárez', 'Coyoacán',
       'Cuajimalpa de Morelos', 'Gustavo A. Madero',
       'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras',
       'Miguel Hidalgo', 'Milpa Alta', 'Tlalpan', 'Tláhuac',
       'Venustiano Carranza', 'Xochimilco', 'Álvaro Obregón'], "No Cuauhtémoc")
df["neighbourhood_cleansed"]

0        No Cuauhtémoc
1           Cuauhtémoc
2           Cuauhtémoc
3        No Cuauhtémoc
4        No Cuauhtémoc
             ...      
26577    No Cuauhtémoc
26578    No Cuauhtémoc
26579    No Cuauhtémoc
26580    No Cuauhtémoc
26581    No Cuauhtémoc
Name: neighbourhood_cleansed, Length: 26582, dtype: object

In [338]:
Vars_Indep=df[['latitude', 'longitude']] #De tipo numérico
Var_Dep=df['neighbourhood_cleansed']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [339]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Cuauhtémoc', 'Cuauhtémoc', 'No Cuauhtémoc', ..., 'Cuauhtémoc',
       'No Cuauhtémoc', 'No Cuauhtémoc'], dtype=object)

In [340]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[2341 1333]
 [1604 2697]]


In [341]:
precision9 = precision_score(y_test, y_pred, average="binary", pos_label="Cuauhtémoc") 
print("Precisión del modelo: ")
print(precision9)

Precisión del modelo: 
0.5934093789607098


In [342]:
precision10 = precision_score(y_test, y_pred, average="binary", pos_label="No Cuauhtémoc") 
print("Precisión del modelo: ")
print(precision10)

Precisión del modelo: 
0.6692307692307692


In [343]:
exactitud5 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud5)

Exactitud del modelo: 
0.6317241379310344


In [344]:
sensibilidad9 = recall_score(y_test, y_pred, average="binary", pos_label="Cuauhtémoc")
print("Sensibilidad del modelo: ")
print(sensibilidad9)

Sensibilidad del modelo: 
0.6371801850843767


In [345]:
sensibilidad10 = recall_score(y_test, y_pred, average="binary", pos_label="No Cuauhtémoc")
print("Sensibilidad del modelo: ")
print(sensibilidad10)

Sensibilidad del modelo: 
0.6270634736107882


**room_type vs accommodates, bathrooms, bedrooms & beds**

In [346]:
unico = np.unique(df["room_type"])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [347]:
df['room_type']= df['room_type'].replace(['Hotel room','Private room', 'Shared room'], "No Entire home")
df["room_type"]

0        Entire home/apt
1        Entire home/apt
2        Entire home/apt
3        Entire home/apt
4        Entire home/apt
              ...       
26577     No Entire home
26578     No Entire home
26579     No Entire home
26580     No Entire home
26581    Entire home/apt
Name: room_type, Length: 26582, dtype: object

In [348]:
Vars_Indep=df[['accommodates','bathrooms','bedrooms','beds']] #De tipo numérico
Var_Dep=df['room_type']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [349]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['No Entire home', 'No Entire home', 'No Entire home', ...,
       'No Entire home', 'No Entire home', 'Entire home/apt'],
      dtype=object)

In [350]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3605 1665]
 [ 429 2276]]


In [351]:
precision11 = precision_score(y_test, y_pred, average="binary", pos_label="Entire home/apt") 
print("Precisión del modelo: ")
print(precision11)

Precisión del modelo: 
0.8936539414972732


In [352]:
precision12 = precision_score(y_test, y_pred, average="binary", pos_label="No Entire home") 
print("Precisión del modelo: ")
print(precision12)

Precisión del modelo: 
0.577518396346105


In [353]:
exactitud6 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud6)

Exactitud del modelo: 
0.7374294670846395


In [354]:
sensibilidad11 = recall_score(y_test, y_pred, average="binary", pos_label="Entire home/apt")
print("Sensibilidad del modelo: ")
print(sensibilidad11)

Sensibilidad del modelo: 
0.6840607210626186


In [355]:
sensibilidad12 = recall_score(y_test, y_pred, average="binary", pos_label="No Entire home")
print("Sensibilidad del modelo: ")
print(sensibilidad12)

Sensibilidad del modelo: 
0.8414048059149722


**accommodates vs price, bathrooms, bedrooms & beds**

In [356]:
df['accommodates']

0        2.0
1        3.0
2        4.0
3        2.0
4        2.0
        ... 
26577    4.0
26578    2.0
26579    2.0
26580    2.0
26581    2.0
Name: accommodates, Length: 26582, dtype: float64

In [357]:
Min = df['accommodates'].min()
Max = df['accommodates'].max()

intervalos = [Min - 1, 3, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["3 o menos", "Más de 3"]

df['accommodates'] = pd.cut(df['accommodates'], bins=intervalos, labels=categorias, right=True)
df['accommodates']

0        3 o menos
1        3 o menos
2         Más de 3
3        3 o menos
4        3 o menos
           ...    
26577     Más de 3
26578    3 o menos
26579    3 o menos
26580    3 o menos
26581    3 o menos
Name: accommodates, Length: 26582, dtype: category
Categories (2, object): ['3 o menos' < 'Más de 3']

In [358]:
df['accommodates'].isnull().sum()

0

In [359]:
Vars_Indep=df[['price','bathrooms','bedrooms','beds']] #De tipo numérico
Var_Dep=df['accommodates']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [360]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['3 o menos', '3 o menos', '3 o menos', ..., '3 o menos',
       '3 o menos', 'Más de 3'], dtype=object)

In [361]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[4721  496]
 [ 570 2188]]


In [362]:
precision13 = precision_score(y_test, y_pred, average="binary", pos_label="Más de 3") 
print("Precisión del modelo: ")
print(precision13)

Precisión del modelo: 
0.8152011922503726


In [363]:
precision14 = precision_score(y_test, y_pred, average="binary", pos_label="3 o menos") 
print("Precisión del modelo: ")
print(precision14)

Precisión del modelo: 
0.8922698922698923


In [364]:
exactitud7 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud7)

Exactitud del modelo: 
0.8663322884012539


In [365]:
sensibilidad13 = recall_score(y_test, y_pred, average="binary", pos_label="Más de 3")
print("Sensibilidad del modelo: ")
print(sensibilidad13)

Sensibilidad del modelo: 
0.7933284989122552


In [366]:
sensibilidad14 = recall_score(y_test, y_pred, average="binary", pos_label="3 o menos")
print("Sensibilidad del modelo: ")
print(sensibilidad14)

Sensibilidad del modelo: 
0.9049262027985432


**reviews_per_month vs number_of_reviews, number_of_reviews_ltm & number_of_reviews_l30d**

In [367]:
df['reviews_per_month']

0        0.00
1        0.41
2        0.31
3        0.83
4        0.11
         ... 
26577    0.00
26578    0.00
26579    0.00
26580    0.00
26581    0.00
Name: reviews_per_month, Length: 26582, dtype: float64

In [368]:
Min = df['reviews_per_month'].min()
Max = df['reviews_per_month'].max()

intervalos = [Min - 1, 1, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["1 o menos", "Más de 1"]

df['reviews_per_month'] = pd.cut(df['reviews_per_month'], bins=intervalos, labels=categorias, right=True)
df['reviews_per_month']

0        1 o menos
1        1 o menos
2        1 o menos
3        1 o menos
4        1 o menos
           ...    
26577    1 o menos
26578    1 o menos
26579    1 o menos
26580    1 o menos
26581    1 o menos
Name: reviews_per_month, Length: 26582, dtype: category
Categories (2, object): ['1 o menos' < 'Más de 1']

In [369]:
Vars_Indep=df[['number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d']]
Var_Dep=df['reviews_per_month']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [370]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Más de 1', 'Más de 1', '1 o menos', ..., 'Más de 1', 'Más de 1',
       '1 o menos'], dtype=object)

In [371]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3916  371]
 [ 545 3143]]


In [372]:
precision15 = precision_score(y_test, y_pred, average="binary", pos_label="Más de 1") 
print("Precisión del modelo: ")
print(precision15)

Precisión del modelo: 
0.8944223107569721


In [373]:
precision16 = precision_score(y_test, y_pred, average="binary", pos_label="1 o menos") 
print("Precisión del modelo: ")
print(precision16)

Precisión del modelo: 
0.8778300829410446


In [374]:
exactitud8 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud8)

Exactitud del modelo: 
0.885141065830721


In [375]:
sensibilidad15 = recall_score(y_test, y_pred, average="binary", pos_label="Más de 1")
print("Sensibilidad del modelo: ")
print(sensibilidad15)

Sensibilidad del modelo: 
0.8522234273318872


In [376]:
sensibilidad16 = recall_score(y_test, y_pred, average="binary", pos_label="1 o menos")
print("Sensibilidad del modelo: ")
print(sensibilidad16)

Sensibilidad del modelo: 
0.91345929554467


**review_scores_rating vs review_scores_cleanliness, review_scores_accuracy, review_scores_checkin, review_scores_communication, review_scores_location & review_scores_value**

In [377]:
df['review_scores_rating']

0        4.80
1        4.58
2        4.90
3        4.91
4        4.91
         ... 
26577    4.80
26578    4.80
26579    4.80
26580    4.80
26581    4.80
Name: review_scores_rating, Length: 26582, dtype: float64

In [378]:
Min = df['review_scores_rating'].min()
Max = df['review_scores_rating'].max()

intervalos = [Min - 1, 4.8, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["Menos de 4.8", "4.8 o más"]

df['review_scores_rating'] = pd.cut(df['review_scores_rating'], bins=intervalos, labels=categorias, right=True)
df['review_scores_rating']

0        Menos de 4.8
1        Menos de 4.8
2           4.8 o más
3           4.8 o más
4           4.8 o más
             ...     
26577    Menos de 4.8
26578    Menos de 4.8
26579    Menos de 4.8
26580    Menos de 4.8
26581    Menos de 4.8
Name: review_scores_rating, Length: 26582, dtype: category
Categories (2, object): ['Menos de 4.8' < '4.8 o más']

In [379]:
Vars_Indep=df[['review_scores_cleanliness','review_scores_accuracy','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value']]
Var_Dep=df['review_scores_rating']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [380]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Menos de 4.8', 'Menos de 4.8', 'Menos de 4.8', ...,
       'Menos de 4.8', '4.8 o más', 'Menos de 4.8'], dtype=object)

In [381]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3290  596]
 [ 316 3773]]


In [382]:
precision17 = precision_score(y_test, y_pred, average="binary", pos_label="4.8 o más") 
print("Precisión del modelo: ")
print(precision17)

Precisión del modelo: 
0.9123682750970604


In [383]:
precision18 = precision_score(y_test, y_pred, average="binary", pos_label="Menos de 4.8") 
print("Precisión del modelo: ")
print(precision18)

Precisión del modelo: 
0.863584344243534


In [384]:
exactitud9 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud9)

Exactitud del modelo: 
0.8856426332288401


In [385]:
sensibilidad17 = recall_score(y_test, y_pred, average="binary", pos_label="4.8 o más")
print("Sensibilidad del modelo: ")
print(sensibilidad17)

Sensibilidad del modelo: 
0.8466289243437982


In [386]:
sensibilidad18 = recall_score(y_test, y_pred, average="binary", pos_label="Menos de 4.8")
print("Sensibilidad del modelo: ")
print(sensibilidad18)

Sensibilidad del modelo: 
0.9227194913181707


**price vs accommodates, bathrooms, bedrooms & beds**

In [387]:
df = pd.read_csv('México por IQR2.csv')
df =df.drop(labels=["Unnamed: 0"], axis=1)
df

id           source  \
0                    35797      city scrape   
1                    44616  previous scrape   
2                    67703      city scrape   
3                    70644      city scrape   
4                   107078      city scrape   
...                    ...              ...   
26577  1252141718111439700      city scrape   
26578  1252159821531694005      city scrape   
26579  1252185591721328995      city scrape   
26580  1252218347521498445      city scrape   
26581  1252229157495978163      city scrape   

                                                   name  \
0                                           Villa Dante   
1                                          Condesa Haus   
2                     2 bedroom apt. deco bldg, Condesa   
3      Beautiful light Studio Coyoacan- full equipped !   
4                                    NEW  DESIGNER LOFT   
...                                                 ...   
26577    Charming 2-Bedroom Retreat in Lomas de Bezares   
26578                     Suite King | District Polanco   
26579                     Suite King | District Polanco   
26580                    Suite Queen | District Polanco   
26581                  Pretty, well centered, amenities   

                                             description  \
0      Dentro de Villa un estudio de arte con futon, ...   
1      A new concept of hosting in mexico through a b...   
2      Comfortably furnished, sunny, 2 bedroom apt., ...   
3      COYOACAN designer studio quiet & safe! well eq...   
4      Is the best ever place triple L <br />Location...   
...                                                  ...   
26577  Experience Mexico City in this delightful retr...   
26578  This spacious room features a plush king-size ...   
26579  Discover the essence of luxury in our king-siz...   
26580  Welcome to your refuge in the heart of Polanco...   
26581  Known as New Polanco, the Granada colony has p...   

                                   neighborhood_overview    host_id  \
0      Santa Fe Mall, Interloma Park and the Lion Des...     153786   
1                                          Not available     196253   
2                                          Not available     334451   
3      Coyoacan is a beautiful neighborhood famous fo...     212109   
4      Is located in the best area of Mexico City, Po...     540705   
...                                                  ...        ...   
26577  Welcome to Lomas de Bezares, a neighborhood kn...   67472234   
26578                                      Not available  596009321   
26579                                      Not available  596009321   
26580                                      Not available  596009321   
26581                                      Not available    6522855   

        host_name  host_response_time host_is_superhost  \
0            Dici  a few days or more                 f   
1        Fernando      within an hour                 t   
2        Nicholas      within an hour                 t   
3          Trisha  within a few hours                 t   
4          Andrea      within an hour                 t   
...           ...                 ...               ...   
26577     HostPal      within an hour                 t   
26578  Luis Angel      within an hour                 f   
26579  Luis Angel      within an hour                 f   
26580  Luis Angel      within an hour                 f   
26581    Salvador      within an hour                 t   

      neighbourhood_cleansed  ... minimum_nights_avg_ntm  \
0      Cuajimalpa de Morelos  ...                    1.0   
1                 Cuauhtémoc  ...                    1.0   
2                 Cuauhtémoc  ...                    2.0   
3                   Coyoacán  ...                    3.7   
4             Miguel Hidalgo  ...                    1.0   
...                      ...  ...                    ...   
26577         Miguel Hidalgo  ...              

In [388]:
df['price']

0        1093.130000
1        1511.712311
2        2029.000000
3        1140.000000
4        1093.130000
            ...     
26577     488.000000
26578    1093.130000
26579    2700.000000
26580    2600.000000
26581    1353.000000
Name: price, Length: 26582, dtype: float64

In [389]:
df['price']=df['price']/22
df['price']

0         49.687727
1         68.714196
2         92.227273
3         51.818182
4         49.687727
            ...    
26577     22.181818
26578     49.687727
26579    122.727273
26580    118.181818
26581     61.500000
Name: price, Length: 26582, dtype: float64

In [390]:
promedio_price = df['price'].mean()
print(promedio_price)

49.687537082619286


In [391]:
Min = df['price'].min()
Max = df['price'].max()

intervalos = [Min - 1,50 , Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["Menos de 50", "50 o más"]

df['price'] = pd.cut(df['price'], bins=intervalos, labels=categorias, right=True)
df['price']

0        Menos de 50
1           50 o más
2           50 o más
3           50 o más
4        Menos de 50
            ...     
26577    Menos de 50
26578    Menos de 50
26579       50 o más
26580       50 o más
26581       50 o más
Name: price, Length: 26582, dtype: category
Categories (2, object): ['Menos de 50' < '50 o más']

In [392]:
Vars_Indep=df[['accommodates','bathrooms','bedrooms','beds']]
Var_Dep=df['price']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [393]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['50 o más', '50 o más', 'Menos de 50', ..., 'Menos de 50',
       '50 o más', '50 o más'], dtype=object)

In [394]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[1431 1910]
 [ 973 3661]]


In [395]:
precision19 = precision_score(y_test, y_pred, average="binary", pos_label="50 o más") 
print("Precisión del modelo: ")
print(precision19)

Precisión del modelo: 
0.5952579034941764


In [396]:
precision20 = precision_score(y_test, y_pred, average="binary", pos_label="Menos de 50") 
print("Precisión del modelo: ")
print(precision20)

Precisión del modelo: 
0.6571531143421289


In [397]:
exactitud10 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud10)

Exactitud del modelo: 
0.6384952978056426


In [398]:
sensibilidad19 = recall_score(y_test, y_pred, average="binary", pos_label="50 o más")
print("Sensibilidad del modelo: ")
print(sensibilidad19)

Sensibilidad del modelo: 
0.4283148757856929


In [399]:
sensibilidad20 = recall_score(y_test, y_pred, average="binary", pos_label="Menos de 50")
print("Sensibilidad del modelo: ")
print(sensibilidad20)

Sensibilidad del modelo: 
0.7900302114803626


In [ ]:
print("Tabla de estadísticos de regresión logística")
print("1 hace referencia a valores true o categorías con valores mayores, 2 a valores false o categorías con valores menores.")
resultados = {
    'Métrica': ['Precisión T o >','Precisión F o <', 'Sensibilidad T o >','Sensibilidad F o >','Exactitud'],
    'instant_bookable': [precision1,precision2,sensibilidad1,sensibilidad2,exactitud1],
    'source': [precision3,precision4,sensibilidad3,sensibilidad4,exactitud2], #city scrape es true, previous scrape es false
    'host_is_superhost': [precision5,precision6,sensibilidad5,sensibilidad6,exactitud3],
    'has_availability': [precision7,precision8,sensibilidad7,sensibilidad8,exactitud4],
    'neighbourhood_group_cleansed': [precision9,precision10,sensibilidad9,sensibilidad10,exactitud5], #Cuauhtémoc es true y No Cuauhtém es false
    'room_type': [precision11,precision12,sensibilidad11,sensibilidad12,exactitud6], #Entire home/apt es true, #No Entire home es false
    'accommodates': [precision13,precision14,sensibilidad13,sensibilidad14,exactitud7], #Más de 3 es true, 3 o menos es false
    'reviews_per_month': [precision15,precision16,sensibilidad15,sensibilidad16,exactitud8], #Más de 1 es true, 1 o menos es false
    'review_scores_rating': [precision17,precision18,sensibilidad17,sensibilidad18,exactitud9], #4.8 o más es true, menos de 4.8 es false
    'price': [precision19,precision20,sensibilidad19,sensibilidad20,exactitud10] # Más de 50 es true, menos de 50 es false
}

# Convertirlo en DataFrame
df_resultados = pd.DataFrame(resultados)

# Mostrar la tabla
df_resultados


Tabla de estadísticos de regresión logística
1 hace referencia a valores true o categorías con valores mayores, 2 a valores false o categorías con valores menores.


Métrica  instant_bookable    source  host_is_superhost  \
0     Precisión T o >          0.548122  0.897589           0.366961   
1     Precisión F o <          0.625298  0.386973           0.613711   
2  Sensibilidad T o >          0.148916  0.977414           0.190820   
3  Sensibilidad F o >          0.920438  0.113356           0.796142   
4           Exactitud          0.617053  0.880878           0.564639   

   has_availability  neighbourhood_group_cleansed  room_type  accommodates  \
0           0.99837                      0.593409   0.893654      0.815201   
1           0.00000                      0.669231   0.577518      0.892270   
2           1.00000                      0.637180   0.684061      0.793328   
3           0.00000                      0.627063   0.841405      0.904926   
4           0.99837                      0.631724   0.737429      0.866332   

   reviews_per_month  review_scores_rating     price  
0           0.894422              0.912368  0.595258  
1           0.877830              0.863584  0.657153  
2           0.852223              0.846629  0.428315  
3           0.913459              0.922719  0.790030  
4           0.885141              0.885643  0.638495