In [3]:
import pandas as pd    
import numpy as np
import matplotlib.pyplot as plt 
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns   
from sklearn.metrics import r2_score   
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('valencia.csv', encoding='utf-8')  # Ajusta sep=',' o ';' si es necesario
df.head(20)

Unnamed: 0       fuente  \
0            0  city scrape   
1            1  city scrape   
2            2  city scrape   
3            3  city scrape   
4            4  city scrape   
5            5  city scrape   
6            6  city scrape   
7            7  city scrape   
8            8  city scrape   
9            9  city scrape   
10          10  city scrape   
11          11  city scrape   
12          12  city scrape   
13          13  city scrape   
14          14  city scrape   
15          15  city scrape   
16          16  city scrape   
17          17  city scrape   
18          18  city scrape   
19          19  city scrape   

                                               nombre  \
0                       Precioso apartamento con wifi   
1                      PENTHOUSE  ON FRONT LINE BEACH   
2           1900 Style Valencian Beach  Home for 10px   
3                ★ Architectural touch! ★   
4                             Apartment near downtown   
5                  Apartments Calatrava City Valencia   
6       Modern 2 br in El Carmen -  Parking Available   
7               Hab. con balcón, cerca de la playa   
8        Habitación cerca de la playa, El Cabanyal   
9                        Apartment Ciudad de Valencia   
10  Sea view apartment with terrace at Cabanyal beach   
11      Queen size bed & private shower by Miguel Inn   
12           Double room, shared bathroom, good water   
13                Design apartment in the center WIFI   
14   Malvabeach family house, WiFi, pool, front beach   
15                Great Room in an apartment,Valencia   
16  Fast.E-360Mbs/Tram 245m/Carmen 390m/On-St parking   
17                  Loft Torres Quart-Valencia Center   
18                    Apartamento centro de Valencia.   
19              Beach Villa,  patio and bbq. Cabanyal   

                                          descripción  \
0   Second floor on a farm from the late 19th cent...   
1                                    Sin descripción   
2   Typical town house with 5 bedrooms and 4 bathr...   
3   Hola! I am ready to welcome you in my apt., wh...   
4                                    Sin descripción   
5                                    Sin descripción   
6   Lovely 2 bedroom 2 bath apartment in the heart...   
7   Sunny room with balcony, facing east. <br />4 ...   
8   Bright room, facing north. <br />4 minutes fro...   
9                                    Sin descripción   
10  Completely renovated flat, on the third floor ...   
11  Bedroom with very confortable queen size bed a...   
12  Experience Valencia from the heart of its best...   
13                                   Sin descripción   
14  Modern house front beach with views over the s...   
15                                   Sin descripción   
16  Enchanting 50m2 spacious luminious studio - pl...   
17  Loft 47m2 on ground floor. It consists on one ...   
18          The apartment is in the Barrio de Ruzafa.   
19  Beautiful apartment on the beachfront. It has ...   

                   descripción general del vecindario  \
0   Very close neighborhood to the city's old town...   
1                          No cuenta con descripción   
2   Surrounded by  historic houses,  authentic res...   
3   Just outside the old city centre (one block aw...   
4   It's a neighborhood with all amenities. 200 me...   
5                          No cuenta con descripción   
6   El Barrio del Carmen is a vibrant real neighbo...   
7                          No cuenta con descripción   
8                          No cuenta con descripción   
9                          No cuenta con descripción   
10  Right next to the house we found a good tapas ...   
11  Our neighborhood is right on the edge of the c...   
12  Exposición neighborhood limints on the sout...   
13                         No cuenta con descripción   
14  It is a very quiet área all year round exce...   
15                         No cuenta con des

In [5]:
df=df.fillna(method="bfill")
df=df.fillna(method="ffill")

C:\Users\isten\AppData\Local\Temp\ipykernel_184\3192995289.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method="bfill")
C:\Users\isten\AppData\Local\Temp\ipykernel_184\3192995289.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method="ffill")


__instant_bookable vs availability_30, host_acceptance_rate, price & beds__

In [6]:
df['reservable_instantáneamente'] = df['reservable_instantáneamente'].replace({'t': 1, 'f': 0})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\2845090898.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['reservable_instantáneamente'] = df['reservable_instantáneamente'].replace({'t': 1, 'f': 0})


In [7]:
Vars_Indep= df[['disponibilidad_30', 'tasa_de_aceptación_host', 'precio', 'baños']]
Var_Dep= df['reservable_instantáneamente']

X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1099  599]
 [ 251  886]]


In [8]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

# Para la clase positiva (1)
precision0 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad0 = recall_score(y_test, y_pred, average="binary", pos_label=1)

# Para la clase negativa (0)
precision1 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad1 = recall_score(y_test, y_pred, average="binary", pos_label=0)

# Exactitud general del modelo
exactitud0 = accuracy_score(y_test, y_pred)

# Imprimir todos los resultados
print("Precisión T:", precision0)
print("Precisión F:", precision1)
print("Sensibilidad T:", sensibilidad0)
print("Sensibilidad F:", sensibilidad1)
print("Exactitud:", exactitud0)

Precisión T: 0.5966329966329966
Precisión F: 0.8140740740740741
Sensibilidad T: 0.7792436235708003
Sensibilidad F: 0.6472320376914017
Exactitud: 0.7001763668430335


__source vs availability_30, price, latitude & longitude__

In [9]:
df['fuente'] = df['fuente'].replace({'city scrape': 1, 'previous scrape': 0})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\4134073855.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['fuente'] = df['fuente'].replace({'city scrape': 1, 'previous scrape': 0})


In [10]:
Vars_Indep0= df[['disponibilidad_30', 'precio', 'longitud']]
Var_Dep0= df['fuente']

X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1124  536]
 [ 290  885]]


In [11]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

# Para la clase positiva (1)
precision2 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad2 = recall_score(y_test, y_pred, average="binary", pos_label=1)

# Para la clase negativa (0)
precision3 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad3 = recall_score(y_test, y_pred, average="binary", pos_label=0)

# Exactitud general del modelo
exactitud1 = accuracy_score(y_test, y_pred)

# Imprimir todos los resultados
print("Precisión T:", precision2)
print("Precisión F:", precision3)
print("Sensibilidad T:", sensibilidad2)
print("Sensibilidad F:", sensibilidad3)
print("Exactitud:", exactitud1)


Precisión T: 0.6228008444757214
Precisión F: 0.7949080622347949
Sensibilidad T: 0.7531914893617021
Sensibilidad F: 0.6771084337349398
Exactitud: 0.7086419753086419


__host_is_superhost vs host_response_rate & review_scores_rating__

In [12]:
df['host_is_superhost'] = df['host_is_superhost'].replace({'t': 1, 'f': 0, 'n':0})
df['tasa_respuesta_host'] = df['tasa_respuesta_host'].str.rstrip('%').astype(float) / 100

C:\Users\isten\AppData\Local\Temp\ipykernel_184\4063263267.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['host_is_superhost'] = df['host_is_superhost'].replace({'t': 1, 'f': 0, 'n':0})


In [13]:
Vars_Indep= df[['tasa_respuesta_host', 'review_scores_rating']]
Var_Dep= df['host_is_superhost']

X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1816  259]
 [ 579  181]]


In [14]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision4 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad4 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision5 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad5 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud2 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision4)
print("Precisión F:", precision5)
print("Sensibilidad T:", sensibilidad4)
print("Sensibilidad F:", sensibilidad5)
print("Exactitud:", exactitud2)

Precisión T: 0.4113636363636364
Precisión F: 0.7582463465553236
Sensibilidad T: 0.2381578947368421
Sensibilidad F: 0.8751807228915662
Exactitud: 0.7044091710758378


__has_availability vs availability_30, price & availability_60__

In [15]:
df['tiene_disponibilidad'] = df['tiene_disponibilidad'].replace({'t': 1, 'f': 0, 'n': 0})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\1277824452.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['tiene_disponibilidad'] = df['tiene_disponibilidad'].replace({'t': 1, 'f': 0, 'n': 0})


In [16]:
Vars_Indep= df[['disponibilidad_30', 'precio', 'disponibilidad_60']]
Var_Dep= df['tiene_disponibilidad']

X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[   0   64]
 [   0 2771]]


In [17]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision6 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad6 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision7 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad7 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud3 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision6)
print("Precisión F:", precision7)
print("Sensibilidad T:", sensibilidad6)
print("Sensibilidad F:", sensibilidad7)
print("Exactitud:", exactitud3)

C:\Users\isten\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Precisión T: 0.9774250440917107
Precisión F: 0.0
Sensibilidad T: 1.0
Sensibilidad F: 0.0
Exactitud: 0.9774250440917107


__neighbourhood_group_cleansed vs latitude & longitude__

In [18]:
df['grupo_vecindario_limpiado'] = df['grupo_vecindario_limpiado'].replace({
    'ALGIROS': 0, 'BENICALAP': 0, 'BENIMACLET': 0, 'CAMPANAR': 0, 'EXTRAMURS': 0,
    'JESUS': 0, "L'EIXAMPLE": 0, 'RASCANYA': 0,
    'CAMINS AL GRAU': 1, 'CIUTAT VELLA': 1, 'EL PLA DEL REAL': 1, "L'OLIVERETA": 1,
    'LA SAIDIA': 1, 'PATRAIX': 1, "POBLATS DE L'OEST": 1, 'POBLATS DEL NORD': 1,
    'POBLATS DEL SUD': 1, 'POBLATS MARITIMS': 1, 'QUATRE CARRERES': 1
})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\3121527802.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['grupo_vecindario_limpiado'] = df['grupo_vecindario_limpiado'].replace({


In [19]:
Vars_Indep= df[['latitud', 'longitud']]
Var_Dep= df['grupo_vecindario_limpiado']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[  92  804]
 [ 167 1772]]


In [20]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision8 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad8 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision9 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad9 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud4 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision8)
print("Precisión F:", precision9)
print("Sensibilidad T:", sensibilidad8)
print("Sensibilidad F:", sensibilidad9)
print("Exactitud:", exactitud4)

Precisión T: 0.687888198757764
Precisión F: 0.3552123552123552
Sensibilidad T: 0.9138731304796287
Sensibilidad F: 0.10267857142857142
Exactitud: 0.6574955908289242


__room_type vs accommodates, bathrooms, bedrooms & beds__

In [21]:
df['tipo_habitación'] = df['tipo_habitación'].replace({ 'Entire home/apt': 0, 'Hotel room': 1, 'Shared room': 1, 'Private room': 1,})
df['se_adapta'] = df['se_adapta'].replace({ '1': 0, '2': 0, '3': 0, '4': 1, '5':1, '6':1, '7':1})
df['dormitorios'] = df['dormitorios'].replace({ '0': 0, '1': 1, '1.4': 1, '2': 1, '3':1})
df['baños'] = df['baños'].replace({ '0.5': 0, '1': 1, '1.2': 1, '1.5': 1, '2':1})
df['camas'] = df['camas'].replace({ '0': 0, '1': 1, '1.9': 1, '2': 1, '3':1, '4':1, '5':1, '6':1})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\2711800175.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['tipo_habitación'] = df['tipo_habitación'].replace({ 'Entire home/apt': 0, 'Hotel room': 1, 'Shared room': 1, 'Private room': 1,})


In [22]:
Vars_Indep= df[['se_adapta', 'dormitorios', 'baños', 'camas']]
Var_Dep= df['tipo_habitación']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1738  287]
 [ 129  681]]


In [23]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision10 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad10 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision11 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad11 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud5 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision10)
print("Precisión F:", precision11)
print("Sensibilidad T:", sensibilidad10)
print("Sensibilidad F:", sensibilidad11)
print("Exactitud:", exactitud5)

Precisión T: 0.7035123966942148
Precisión F: 0.9309051955008034
Sensibilidad T: 0.8407407407407408
Sensibilidad F: 0.8582716049382716
Exactitud: 0.85326278659612


__accommodates vs price, bathrooms, bedrooms & beds__

In [24]:
df['se_adapta'] = df['se_adapta'].replace({1: 0, 2: 0, 3: 0, 3.2: 1, 4: 1, 5: 1, 6: 1, 7: 1})

In [25]:
df['se_adapta'] = df['se_adapta'].astype(int)

In [26]:
Vars_Indep= df[['precio', 'dormitorios', 'baños', 'camas']]
Var_Dep= df['se_adapta']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1280  150]
 [ 350 1055]]


In [27]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision12 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad12 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision13 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad13 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud6 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision12)
print("Precisión F:", precision13)
print("Sensibilidad T:", sensibilidad12)
print("Sensibilidad F:", sensibilidad13)
print("Exactitud:", exactitud6)

Precisión T: 0.8755186721991701
Precisión F: 0.7852760736196319
Sensibilidad T: 0.7508896797153025
Sensibilidad F: 0.8951048951048951
Exactitud: 0.8236331569664903


__reviews_per_month vs number_of_reviews, number_of_reviews_ltm & number_of_reviews_l30__

In [28]:
df['reseñas_por_mes'] = np.where(df['reseñas_por_mes'] <= 3, "Menor o igual a 3", "Mayor a 3")

In [29]:
df['reseñas_por_mes'] = df['reseñas_por_mes'].replace({"Menor o igual a 3": 0, "Mayor a 3": 1})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\2858161777.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['reseñas_por_mes'] = df['reseñas_por_mes'].replace({"Menor o igual a 3": 0, "Mayor a 3": 1})


In [30]:
Vars_Indep= df[['número_de_reseñas', 'número_de_reviews_ltm', 'número_de_reviews_l30d']]
Var_Dep= df['reseñas_por_mes']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[2244  136]
 [ 289  166]]


In [31]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision14 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad14 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision15 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad15 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud7 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision14)
print("Precisión F:", precision15)
print("Sensibilidad T:", sensibilidad14)
print("Sensibilidad F:", sensibilidad15)
print("Exactitud:", exactitud7)

Precisión T: 0.5496688741721855
Precisión F: 0.8859060402684564
Sensibilidad T: 0.3648351648351648
Sensibilidad F: 0.9428571428571428
Exactitud: 0.8500881834215167


__review_scores_rating vs review_scores_cleanliness, review_scores_accuracy, review_scores_checkin, review_scores_communication, review_scores_location & review_scores_value__

In [34]:
df['review_scores_rating'] = np.where(df['review_scores_rating'] <= 4, "Menor o igual a 4", "Mayor a 4")

In [35]:
df['review_scores_rating'] = df['review_scores_rating'].replace({"Menor o igual a 4": 0, "Mayor a 4": 1})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\1557239457.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['review_scores_rating'] = df['review_scores_rating'].replace({"Menor o igual a 4": 0, "Mayor a 4": 1})


In [38]:
Vars_Indep= df[['review_scores_cleanliness', 'review_scores_accuracy', 'review_scores_checkin', 'review_scores_comunicación', 'review_scores_location', 'review_scores_value']]
Var_Dep= df['review_scores_rating']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[  45   69]
 [  21 2700]]


In [39]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision16 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad16 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision17 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad17 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud8 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision16)
print("Precisión F:", precision17)
print("Sensibilidad T:", sensibilidad16)
print("Sensibilidad F:", sensibilidad17)
print("Exactitud:", exactitud8)

Precisión T: 0.9750812567713976
Precisión F: 0.6818181818181818
Sensibilidad T: 0.9922822491730982
Sensibilidad F: 0.39473684210526316
Exactitud: 0.9682539682539683


__price vs accommodates, bathrooms, bedrooms & beds__

In [41]:
df['precio'] = np.where(df['precio'] <= 100, "Menor o igual a 100", "Mayor a 100")

In [42]:
df['precio'] = df['precio'].replace({"Menor o igual a 100": 0, "Mayor a 100": 1})

C:\Users\isten\AppData\Local\Temp\ipykernel_184\4174052947.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['precio'] = df['precio'].replace({"Menor o igual a 100": 0, "Mayor a 100": 1})


In [44]:
Vars_Indep= df[['se_adapta', 'baños', 'dormitorios', 'camas']]
Var_Dep= df['precio']
X= Vars_Indep
y= Var_Dep

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=None)

escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[1316  362]
 [ 341  816]]


In [45]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

precision18 = precision_score(y_test, y_pred, average="binary", pos_label=1)
sensibilidad18 = recall_score(y_test, y_pred, average="binary", pos_label=1)

precision19 = precision_score(y_test, y_pred, average="binary", pos_label=0)
sensibilidad19 = recall_score(y_test, y_pred, average="binary", pos_label=0)

exactitud9 = accuracy_score(y_test, y_pred)

print("Precisión T:", precision18)
print("Precisión F:", precision19)
print("Sensibilidad T:", sensibilidad18)
print("Sensibilidad F:", sensibilidad19)
print("Exactitud:", exactitud9)

Precisión T: 0.6926994906621392
Precisión F: 0.7942063971031985
Sensibilidad T: 0.7052722558340536
Sensibilidad F: 0.7842669845053635
Exactitud: 0.7520282186948853


__TABLA__

In [46]:
print("Tabla de regresión logistica")
resultados = {
    'Simbologia':['Presición T', 'Precisión F', 'Sensibilidad T', 'Sensbilidad F', 'Exactitud'],
    'reservable_instantáneamente' :[precision0, precision1, sensibilidad0, sensibilidad1, exactitud0],
    'fuente' : [precision2, precision3, sensibilidad2, sensibilidad3, exactitud1],
    'host_is_superhost' : [precision4, precision5, sensibilidad4, sensibilidad5, exactitud2],
    'tiene_disponibilidad' : [precision6, precision7, sensibilidad6, sensibilidad7, exactitud3],
    'grupo_vecindario_limpiado':[precision8, precision9, sensibilidad8, sensibilidad9, exactitud4],
    'tipo_habitación':[precision10, precision11, sensibilidad10, sensibilidad11, exactitud5],
    'se_adapta':[precision12, precision13, sensibilidad12, sensibilidad13, exactitud6],
    'reseñas_por_mes':[precision14, precision15, sensibilidad14, sensibilidad15, exactitud7],
    'review_scores_rating':[precision16,precision17, sensibilidad16, sensibilidad17, exactitud8],
    'precio':[precision18, precision19, sensibilidad18, sensibilidad19, exactitud9]
    
}

df_r=pd.DataFrame(resultados)
df_r

Tabla de regresión logistica


Simbologia  reservable_instantáneamente    fuente  host_is_superhost  \
0     Presición T                     0.596633  0.622801           0.411364   
1     Precisión F                     0.814074  0.794908           0.758246   
2  Sensibilidad T                     0.779244  0.753191           0.238158   
3   Sensbilidad F                     0.647232  0.677108           0.875181   
4       Exactitud                     0.700176  0.708642           0.704409   

   tiene_disponibilidad  grupo_vecindario_limpiado  tipo_habitación  \
0              0.977425                   0.687888         0.703512   
1              0.000000                   0.355212         0.930905   
2              1.000000                   0.913873         0.840741   
3              0.000000                   0.102679         0.858272   
4              0.977425                   0.657496         0.853263   

   se_adapta  reseñas_por_mes  review_scores_rating    precio  
0   0.875519         0.549669              0.975081  0.692699  
1   0.785276         0.885906              0.681818  0.794206  
2   0.750890         0.364835              0.992282  0.705272  
3   0.895105         0.942857              0.394737  0.784267  
4   0.823633         0.850088              0.968254  0.752028